version: 1
disable_existing_loggers: no
formatters:
        normal:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        simple:
            format: "%(name)s - %(levelname)s - %(message)s"

root:
    level: INFO
    handlers: [console_handler,file_handler]

loggers:
    crawler:
        level: INFO
        handlers: [ console_handler,file_handler ]
        propagate: no

handlers:
    console_handler:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
    file_handler:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: "./log/history.log"